# Generated by Django 6.0.2 on 2026-06-17 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('product', 'Product'), ('expense', 'Expense'), ('material', 'Material')], default='material', max_length=100)),
                ('target_margin', models.PositiveSmallIntegerField(blank=True, help_text='Default profit margin % for products in this category (Product categories only). Blank = global default.', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)])),
            ],
        ),
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page', models.CharField(choices=[('products', 'Products'), ('suppliers', 'Suppliers'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('dashboard', 'Dashboard')], max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('paid', 'Paid'), ('canceled', 'Canceled')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
