# Generated by Django 6.0.2 on 2026-07-31 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'created_by'], name='core_catego_busines_f02c29_idx'),
        ),
    ]
