# Generated by Django 6.0.2 on 2026-03-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('item', 'Item'), ('product', 'Product'), ('expense', 'Expense'), ('material', 'Material')], default='material', max_length=100),
        ),
    ]
