# Generated by Django 6.0.2 on 2026-03-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
