# Generated by Django 6.0.2 on 2026-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_category_unique_together_category_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('product', 'Product'), ('expense', 'Expense'), ('material', 'Material')], default='material', max_length=100),
        ),
    ]
