# Generated by Django 6.0.2 on 2026-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_category_type'),
        ('user', '0006_alter_businessprofile_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page', models.CharField(choices=[('products', 'Products'), ('suppliers', 'Suppliers'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('dashboard', 'Dashboard')], max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='user.businessprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'page', '-date'], name='core_kpisna_busines_5e08cc_idx')],
                'unique_together': {('business', 'date', 'page')},
            },
        ),
    ]
