# Generated by Django 6.0.2 on 2026-06-17 06:42

import core.utils.images
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.images.product_image_path)),
                ('image_original_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('cost_price', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('prepared_quantity', models.PositiveIntegerField()),
                ('default_quantity', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=25, help_text='Alert when stock drops to or below this level')),
                ('high_stock_threshold', models.PositiveIntegerField(default=50, help_text='Considered fully stocked at or above this level')),
                ('target_margin', models.PositiveSmallIntegerField(blank=True, help_text='Desired profit margin % for this product. Blank = use category, then global default.', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)])),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_service', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPresetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
