# Generated by Django 6.0.2 on 2026-06-27 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_session_based',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ServiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Product.product')),
            ],
            options={
                'ordering': ['sort_order', 'minutes', 'id'],
            },
        ),
    ]
