# Generated by Django 6.0.2 on 2026-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_is_session_based_servicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_class',
            field=models.CharField(choices=[('vatable', 'VATable (12%)'), ('exempt', 'VAT-Exempt'), ('zero', 'Zero-Rated (0%)')], default='vatable', help_text="VAT treatment when your business is VAT-registered. Most goods are VATable; certain maintenance medicines and basic goods are VAT-Exempt. Ignored while you're Non-VAT.", max_length=8),
        ),
    ]
