# Generated by Django 6.0.2 on 2026-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_vat_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productpresetitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
