# Generated by Django 6.0.2 on 2026-07-31 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_cost_price_alter_product_selling_price_and_more'),
        ('Supplier', '0005_backfill_material_sku'),
        ('core', '0003_category_core_catego_busines_f02c29_idx'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'created_by'], name='Product_pro_busines_184829_idx'),
        ),
        migrations.AddIndex(
            model_name='productpreset',
            index=models.Index(fields=['business', 'created_by'], name='Product_pro_busines_fd37f0_idx'),
        ),
    ]
