# Generated by Django 6.0.2 on 2026-03-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_product_cost_price_alter_product_selling_price'),
        ('Supplier', '0004_alter_material_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Supplier.material'),
        ),
    ]
