# Generated by Django 6.0.2 on 2026-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
