# Generated by Django 6.0.2 on 2026-04-11 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_product_slug'),
        ('user', '0009_businessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='user.businessprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'slug', 'business')},
        ),
    ]
