# Generated by Django 6.0.2 on 2026-04-28 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_alter_product_created_at_and_more'),
        ('user', '0003_alter_businessprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productpreset',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_presets', to='user.businessprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='productpreset',
            unique_together={('user', 'business', 'name')},
        ),
    ]
