# Generated by Django 6.0.2 on 2026-04-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_productpreset_business_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpreset',
            unique_together=set(),
        ),
    ]
