# Generated by Django 6.0.2 on 2026-05-03 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_alter_productpreset_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpreset',
            unique_together={('user', 'name')},
        ),
    ]
