# Generated by Django 6.0.2 on 2026-05-03 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_alter_productpreset_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpreset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productpreset',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productpreset',
            unique_together={('user', 'name', 'slug')},
        ),
    ]
