# Generated by Django 6.0.2 on 2026-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_alter_productpreset_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpresetitem',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
