# Generated by Django 6.0.2 on 2026-05-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_productpresetitem_supplier_name'),
        ('user', '0005_alter_businessprofile_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpreset',
            unique_together={('business', 'name')},
        ),
    ]
