# Generated by Django 6.0.2 on 2026-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_alter_productpreset_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpreset',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
