# Generated by Django 6.0.2 on 2026-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_alter_productpreset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpreset',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productpreset',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
