# Generated by Django 6.0.2 on 2026-05-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_product_is_locked_product_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
