# Generated by Django 6.0.2 on 2026-05-30 20:26

import core.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_product_barcode_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.images.product_image_path),
        ),
    ]
