# Generated by Django 6.0.2 on 2026-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
