# Generated by Django 6.0.2 on 2026-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(db_index=True, default=False)),
                ('pending_cancellation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CancellationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_at_cancel', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=20)),
                ('months_used', models.PositiveIntegerField()),
                ('cycle_end_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_day_15_sent', models.BooleanField(default=False)),
                ('reminder_day_30_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FounderInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FounderSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_total', models.PositiveIntegerField(default=10)),
                ('slots_claimed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.CharField(choices=[('single', 'Single Business'), ('dual', '2 Businesses'), ('triple', '3 Businesses')], default='triple', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('payment_method', models.CharField(choices=[('installment', 'Monthly installments'), ('upfront', 'Yearly upfront')], default='installment', max_length=20)),
                ('is_founder', models.BooleanField(default=False)),
                ('is_lifetime', models.BooleanField(default=False)),
                ('trial_used', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
