# Generated by Django 6.0.2 on 2026-07-07 10:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationinvoice',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='cancellationinvoice',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cancellationinvoice',
            name='status',
            field=models.CharField(choices=[('none', 'No refund'), ('pending', 'Refund pending'), ('refunded', 'Refunded')], default='none', max_length=20),
        ),
    ]
