# Generated by Django 6.0.2 on 2026-05-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_backfill_businessplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
    ]
