# Generated by Django 6.0.2 on 2026-07-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_cancellationinvoice_amount_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationinvoice',
            name='status',
            field=models.CharField(choices=[('none', 'No refund'), ('pending', 'Refund pending'), ('refunded', 'Refunded'), ('voided', 'Voided (cancellation undone)')], default='none', max_length=20),
        ),
    ]
