# Generated by Django 6.0.2 on 2026-05-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_backfill_bundle_triple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='bundle',
            field=models.CharField(choices=[('single', 'Single Business'), ('dual', '2 Businesses'), ('triple', '3 Businesses')], default='triple', max_length=20),
        ),
    ]
