# Generated by Django 6.0.2 on 2026-07-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscription_billing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancellationinvoice',
            name='plan_at_cancel',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20),
        ),
    ]
