# Generated by Django 6.0.2 on 2026-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscription_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='is_trial',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
