# Generated by Django 6.0.2 on 2026-05-28 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_businessplan_is_trial'),
        ('user', '0005_alter_businessprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='pending_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('installment', 'Monthly installments'), ('upfront', 'Yearly upfront')], default='installment', max_length=20),
        ),
        migrations.CreateModel(
            name='CancellationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_at_cancel', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('pro', 'Pro')], max_length=20)),
                ('months_used', models.PositiveIntegerField()),
                ('cycle_end_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_day_15_sent', models.BooleanField(default=False)),
                ('reminder_day_30_sent', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_invoices', to='user.businessprofile')),
            ],
        ),
    ]
