# Generated by Django 6.0.2 on 2026-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='shared_cash_drawer',
            field=models.BooleanField(default=True, help_text='On: one drawer handed over between cashiers across shifts (AM→PM), with a recount at each handover. Off: each cashier has their own till.'),
        ),
    ]
