# Generated by Django 6.0.2 on 2026-06-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_businessprofile_enable_purchase_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_business',
            field=models.ForeignKey(blank=True, help_text='Set when a staff verified email but awaits owner approval. Cleared on approval.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_staff', to='user.businessprofile'),
        ),
    ]
