# Generated by Django 6.0.2 on 2026-06-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_pending_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='dashboard_basis',
            field=models.CharField(choices=[('accrual', 'Business Performance'), ('cash', 'Cash Flow')], default='accrual', help_text='Default lens for the dashboard KPIs. Owners can flip transiently on the dashboard.', max_length=10),
        ),
    ]
