# Generated by Django 6.0.2 on 2026-07-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_businessprofile_dashboard_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Light or dark look for the whole app. Personal to each user.', max_length=10),
        ),
    ]
