# Generated by Django 6.0.2 on 2026-07-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidebar_theme',
            field=models.CharField(choices=[('match', 'Match app'), ('light', 'Light'), ('dark', 'Dark')], default='match', help_text='The sidebar can follow the app theme or stay light/dark on its own.', max_length=10),
        ),
    ]
