# Generated by Django 6.0.2 on 2026-06-17 06:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(choices=[('owner_drawing', 'Owner personal withdrawal'), ('change_float', 'Add to change float'), ('petty_cash', 'Petty cash'), ('other', 'Other')], default='owner_drawing', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('default_opening_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Override business default for this employee. Leave blank to use business default.', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningCashChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(help_text="Owner's required reason for change.")),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningCashOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, help_text="e.g. 'Holiday rush' or 'Payday weekend'", max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clock_in', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('opening_bills', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('opening_coins', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('staff_confirmed_opening', models.BooleanField(default=False)),
                ('staff_confirmed_opening_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counted_bills', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counted_coins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counted_gcash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counted_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closing_note', models.TextField(blank=True, help_text='Explain any variance.')),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
