# Generated by Django 6.0.2 on 2026-06-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayout',
            name='purpose',
            field=models.CharField(choices=[('business_expense', 'Business expense (booked to expenses)'), ('owner_drawing', 'Owner personal withdrawal'), ('change_float', 'Add to change float'), ('petty_cash', 'Petty cash'), ('other', 'Other')], default='owner_drawing', max_length=30),
        ),
    ]
