# Generated by Django 6.0.2 on 2026-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_cashpayout_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayout',
            name='purpose',
            field=models.CharField(choices=[('business_expense', 'For the business (added to expenses)'), ('owner_drawing', 'Owner took personal use'), ('change_float', 'For change money'), ('petty_cash', 'Small expense'), ('other', 'Other')], default='owner_drawing', max_length=30),
        ),
    ]
