# Generated by Django 6.0.2 on 2026-06-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_cashpayout_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
