# Generated by Django 6.0.2 on 2026-06-19 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_employee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftemployee',
            name='close_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='close_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='close_reason',
            field=models.TextField(blank=True, help_text="Owner's required reason for timing out the staff on their behalf."),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_closed_shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
