# Generated by Django 6.0.2 on 2026-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_shiftemployee_close_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_cashier',
            field=models.BooleanField(default=False, help_text='Handles a cash drawer (gets the starting-cash + cash-count flow). Off = attendance & payroll only.'),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
    ]
