# Generated by Django 6.0.2 on 2026-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_employee_is_cashier_shiftemployee_is_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftemployee',
            name='close_dispute_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='close_dispute_reason',
            field=models.CharField(blank=True, choices=[('counted_different', 'I counted a different amount'), ('please_recount', 'Please recount the drawer'), ('cash_not_recorded', "A cash in/out wasn't recorded"), ('did_time_out', "I didn't forget — I timed out"), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='close_dispute_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
