# Generated by Django 6.0.2 on 2026-06-20 18:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_shiftemployee_close_dispute_note_and_more'),
        ('user', '0002_businessprofile_shared_cash_drawer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawer_sessions', to='user.businessprofile')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Employee.shiftemployee')),
            ],
            options={
                'ordering': ['-date', '-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='drawer_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_employees', to='Employee.drawersession'),
        ),
    ]
