# Generated by Django 6.0.2 on 2026-06-20 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_drawersession_shiftemployee_drawer_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drawer_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='Employee.drawersession')),
                ('from_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_out', to='Employee.shiftemployee')),
                ('to_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_in', to='Employee.shiftemployee')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
