# Generated by Django 6.0.2 on 2026-06-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_handover'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handover',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
