# Generated by Django 6.0.2 on 2026-07-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_handover_reviewed_handover_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_handle_payables',
            field=models.BooleanField(default=False, help_text='Can see and settle supplier bills (payables). Off = the payables table is hidden for this staff.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_handle_receivables',
            field=models.BooleanField(default=False, help_text='Can see and collect customer debt (receivables). Off = the receivables table is hidden for this staff.'),
        ),
    ]
