# Generated by Django 6.0.2 on 2026-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_backfill_shift_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftemployee',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='auto_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
