# Generated by Django 6.0.2 on 2026-07-31 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0014_shiftemployee_auto_closed_and_more'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drawersession',
            index=models.Index(fields=['business', 'date'], name='Employee_dr_busines_922bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='openingcashoverride',
            index=models.Index(fields=['business', 'date'], name='Employee_op_busines_fc7a24_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['business', 'date'], name='Employee_sh_busines_943674_idx'),
        ),
    ]
