# Generated by Django 6.0.2 on 2026-07-31 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_drawersession_employee_dr_busines_922bc9_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shift',
            new_name='Employee_sh_busines_73beab_idx',
            old_name='Employee_sh_busines_943674_idx',
        ),
    ]
