# Generated by Django 6.0.2 on 2026-07-31 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_stock_price'),
        ('Supplier', '0005_backfill_material_sku'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['business', 'unit', 'created_by'], name='Inventory_s_busines_6a5d4d_idx'),
        ),
    ]
