# Generated by Django 6.0.2 on 2026-03-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_stock_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
