# Generated by Django 6.0.2 on 2026-04-28 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_alter_stock_created_at'),
        ('Supplier', '0015_alter_supplier_unique_together'),
        ('user', '0003_alter_businessprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('user', 'business', 'material')},
        ),
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
