# Generated by Django 6.0.2 on 2026-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiscExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('cash', 'Cash'), ('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('credit', 'Credit / Other')], default='cod', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('defective', 'Defective'), ('wrong_item', 'Wrong item'), ('expired', 'Expired'), ('damaged_delivery', 'Damaged in delivery'), ('qty_correction', 'Quantity correction'), ('amount_correction', 'Amount correction'), ('staff_error', 'Staff error'), ('other', 'Other')], default='defective', max_length=30)),
                ('reason_note', models.CharField(blank=True, max_length=255)),
                ('refund_total', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash refund'), ('credit', 'Credit on outstanding balance')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_refund', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('reason', models.CharField(choices=[('spoilage', 'Spoilage'), ('expired', 'Expired'), ('damage', 'Damage'), ('defective', 'Defective'), ('personal_use', 'Personal Use'), ('service', 'Service Use'), ('theft', 'Theft'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
