# Generated by Django 6.0.2 on 2026-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_purchaseitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
