# Generated by Django 6.0.2 on 2026-06-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0003_purchase_is_void_purchase_void_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
