# Generated by Django 6.0.2 on 2026-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0004_wasteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
