# Generated by Django 6.0.2 on 2026-03-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0004_waste_wasteitem'),
        ('Product', '0007_alter_product_cost_price_alter_product_selling_price'),
        ('Supplier', '0003_material_piece_per_unit_alter_material_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_items', to='Supplier.material'),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_items', to='Product.product'),
        ),
    ]
