# Generated by Django 6.0.2 on 2026-03-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0005_alter_wasteitem_material_alter_wasteitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
