# Generated by Django 6.0.2 on 2026-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0006_wasteitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
