# Generated by Django 6.0.2 on 2026-03-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0007_purchaseitem_name'),
        ('Supplier', '0004_alter_material_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Supplier.material'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='Expense.purchase'),
        ),
    ]
