# Generated by Django 6.0.2 on 2026-03-23 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0008_alter_purchaseitem_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_items', to='Expense.waste'),
        ),
    ]
