# Generated by Django 6.0.2 on 2026-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0008_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='refund_cash',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='refund_credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'Cash refund'), ('credit', 'Credit on outstanding balance'), ('mixed', 'Credit + cash')], default='cash', max_length=20),
        ),
    ]
