# Generated by Django 6.0.2 on 2026-03-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0009_alter_wasteitem_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
