# Generated by Django 6.0.2 on 2026-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0010_wasteitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
