# Generated by Django 6.0.2 on 2026-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0010_backfill_refund_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='refund_cash',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='refund_credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='refund_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_refund',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='waste',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
