# Generated by Django 6.0.2 on 2026-07-30 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0011_alter_purchase_discount_amount_and_more'),
        ('core', '0002_initial'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='outstanding',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['business', 'status', '-reference'], name='Expense_pur_busines_29f0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['business', 'is_void', 'status', 'voided_at'], name='Expense_pur_busines_1927a0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['business', 'status', 'created_by'], name='Expense_pur_busines_03fec2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(condition=models.Q(('outstanding__gt', 0)), fields=['business'], name='sale_receivable_idx'),
        ),
    ]
