# Generated by Django 6.0.2 on 2026-07-31 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0012_purchase_outstanding_purchase_total_quantity_and_more'),
        ('core', '0002_initial'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'date', 'created_by'], name='Expense_exp_busines_34569f_idx'),
        ),
        migrations.AddIndex(
            model_name='miscexpense',
            index=models.Index(fields=['business', 'created_by'], name='Expense_mis_busines_8b43ac_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['business', 'date', 'created_by'], name='Expense_pur_busines_7abcff_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['business', 'date', 'created_by'], name='Expense_pur_busines_f7c621_idx'),
        ),
        migrations.AddIndex(
            model_name='waste',
            index=models.Index(fields=['business', 'date', 'created_by'], name='Expense_was_busines_b56488_idx'),
        ),
    ]
