# Generated by Django 6.0.2 on 2026-04-28 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0016_remove_expense_misc_expense_remove_expense_name_and_more'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='user.businessprofile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='user.businessprofile'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='user.businessprofile'),
        ),
        migrations.AddField(
            model_name='waste',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastes', to='user.businessprofile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('user', 'business', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('user', 'business')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'business')},
        ),
        migrations.AlterUniqueTogether(
            name='waste',
            unique_together={('user', 'business')},
        ),
    ]
