# Generated by Django 6.0.2 on 2026-04-11 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0017_employee_business_employee_slug_alter_employee_name_and_more'),
        ('user', '0009_businessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='user.businessprofile'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='user.businessprofile'),
        ),
        migrations.AddField(
            model_name='waste',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastes', to='user.businessprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('user', 'business')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'business')},
        ),
        migrations.AlterUniqueTogether(
            name='waste',
            unique_together={('user', 'business')},
        ),
    ]
