# Generated by Django 6.0.2 on 2026-04-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0018_alter_employee_created_at_alter_expense_created_at_and_more'),
        ('user', '0003_alter_businessprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='waste',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='miscexpense',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misc_expenses', to='user.businessprofile'),
        ),
        migrations.AddField(
            model_name='shift',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='user.businessprofile'),
        ),
    ]
