# Generated by Django 6.0.2 on 2026-05-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0019_alter_expense_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
