# Generated by Django 6.0.2 on 2026-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0020_expenseitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
