# Generated by Django 6.0.2 on 2026-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0021_employee_is_locked_employee_locked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
