# Generated by Django 6.0.2 on 2026-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0022_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='reason',
            field=models.CharField(choices=[('spoilage', 'Spoilage'), ('damage', 'Damage'), ('personal_use', 'Personal Use'), ('theft', 'Theft'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
