# Generated by Django 6.0.2 on 2026-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0023_waste_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
