# Generated by Django 6.0.2 on 2026-06-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0024_alter_waste_date'),
        ('user', '0006_alter_businessprofile_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='reason',
            field=models.CharField(choices=[('spoilage', 'Spoilage'), ('expired', 'Expired'), ('damage', 'Damage'), ('defective', 'Defective'), ('personal_use', 'Personal Use'), ('theft', 'Theft'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('cash', 'Cash'), ('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('credit', 'Credit / Other')], default='cod', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payments', to='user.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Expense.purchase')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('defective', 'Defective'), ('wrong_item', 'Wrong item'), ('expired', 'Expired'), ('damaged_delivery', 'Damaged in delivery'), ('qty_correction', 'Quantity correction'), ('amount_correction', 'Amount correction'), ('void', "Void / shouldn't have happened"), ('staff_error', 'Staff error'), ('other', 'Other')], default='defective', max_length=30)),
                ('reason_note', models.CharField(blank=True, max_length=255)),
                ('refund_total', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash refund'), ('credit', 'Credit on outstanding balance')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='user.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('original_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='Expense.purchase')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_refund', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('resellable', models.BooleanField(default=True)),
                ('original_purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='Expense.purchaseitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Expense.purchasereturn')),
            ],
        ),
    ]
