# Generated by Django 6.0.2 on 2026-06-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0025_purchase_due_date_alter_waste_reason_purchasepayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='resellable',
        ),
    ]
