# Generated by Django 6.0.2 on 2026-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0026_remove_purchasereturnitem_resellable'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
