# Generated by Django 6.0.2 on 2026-06-01 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0006_alter_businessprofile_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('product.created', 'Product created'), ('product.updated', 'Product updated'), ('product.archived', 'Product archived'), ('product.restored', 'Product restored'), ('material.created', 'Material created'), ('material.updated', 'Material updated'), ('material.archived', 'Material archived'), ('material.restored', 'Material restored'), ('supplier.created', 'Supplier added'), ('supplier.updated', 'Supplier updated'), ('supplier.archived', 'Supplier archived'), ('sale.completed', 'Sale completed'), ('purchase.recorded', 'Purchase recorded'), ('stock.adjusted', 'Stock updated'), ('stock.low', 'Low stock alert'), ('stock.out', 'Out of stock'), ('trial.ending', 'Trial ending soon'), ('plan.expired', 'Plan expired'), ('plan.canceled', 'Subscription canceled'), ('staff.added', 'Staff added')], db_index=True, max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_important', models.BooleanField(db_index=True, default=False)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='user.businessprofile')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='activity_ac_busines_9aa723_idx'), models.Index(fields=['business', 'is_important', 'is_read'], name='activity_ac_busines_a5da66_idx')],
            },
        ),
    ]
