# Generated by Django 6.0.2 on 2026-06-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auditlog'),
        ('user', '0002_businessprofile_shared_cash_drawer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_salary_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expense_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to='user.businessprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['business', '-date'], name='activity_da_busines_8238e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'date'), name='uniq_dailyclose_business_date')],
            },
        ),
    ]
