# Generated by Django 6.0.2 on 2026-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activityevent_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('product.created', 'Product created'), ('product.updated', 'Product updated'), ('product.archived', 'Product archived'), ('product.restored', 'Product restored'), ('material.created', 'Material created'), ('material.updated', 'Material updated'), ('material.archived', 'Material archived'), ('material.restored', 'Material restored'), ('supplier.created', 'Supplier added'), ('supplier.updated', 'Supplier updated'), ('supplier.archived', 'Supplier archived'), ('supplier.restore', 'Supplier restored'), ('sale.completed', 'Sale completed'), ('sale.reference', 'Sale reference'), ('purchase.recorded', 'Purchase recorded'), ('purchase.reference', 'Purchase reference'), ('stock.adjusted', 'Stock updated'), ('stock.low', 'Low stock alert'), ('stock.out', 'Out of stock'), ('waste.recorded', 'Waste recorded'), ('trial.ending', 'Trial ending soon'), ('plan.expired', 'Plan expired'), ('plan.canceled', 'Subscription canceled'), ('staff.added', 'Staff added')], db_index=True, max_length=40),
        ),
    ]
