# Generated by Django 6.0.2 on 2026-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_dailyclose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('product.created', 'Product created'), ('product.updated', 'Product updated'), ('product.archived', 'Product archived'), ('product.restored', 'Product restored'), ('product.margin_low', 'Margin critically low'), ('material.created', 'Material created'), ('material.updated', 'Material updated'), ('material.archived', 'Material archived'), ('material.restored', 'Material restored'), ('supplier.created', 'Supplier added'), ('supplier.updated', 'Supplier updated'), ('supplier.archived', 'Supplier archived'), ('supplier.restore', 'Supplier restored'), ('sale.completed', 'Sale completed'), ('sale.reference', 'Sale reference'), ('sale.paid', 'Sale payment recorded'), ('purchase.recorded', 'Purchase recorded'), ('purchase.reference', 'Purchase reference'), ('purchase.paid', 'Purchase payment recorded'), ('stock.adjusted', 'Stock updated'), ('stock.low', 'Low stock alert'), ('stock.out', 'Out of stock'), ('waste.recorded', 'Waste recorded'), ('trial.ending', 'Trial ending soon'), ('plan.expired', 'Plan expired'), ('plan.canceled', 'Subscription canceled'), ('plan.expiring', 'Subscription ending soon'), ('staff.added', 'Staff added'), ('purchase.refunded', 'Purchase refunded'), ('sale.refunded', 'Sale refunded')], db_index=True, max_length=40),
        ),
    ]
