# Generated by Django 6.0.2 on 2026-07-13 01:30

from django.db import migrations, models


def drop_stale_closes(apps, schema_editor):
    """Delete every existing DailyClose so past days RE-FREEZE on the new profit formula.

    A DailyClose is normally append-only — "pen, not pencil". Deleting them is a deliberate
    one-off, and it is the honest move rather than a violation of that rule: these rows were
    frozen under a formula that subtracted stock PURCHASED, so they hold a `net_profit` this
    codebase no longer computes and a `total_cogs` of 0 that was never measured. Backfilling
    total_cogs would be worse — it would produce rows whose columns don't sum to the frozen
    net_profit beside them, i.e. a sealed day that visibly doesn't add up.

    Safe here because the owner confirmed every existing close is dummy/dev data. The days
    re-close automatically the next time the Daily Summary reads them.

    IF THIS EVER RUNS AGAINST REAL BOOKS, DON'T. Freeze rows are the audit trail; on live
    data the correct move is a forward-dated adjustment, never a delete.
    """
    apps.get_model('activity', 'DailyClose').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activityevent_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclose',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        # Reverse is a no-op: nothing to restore, and the rows rebuild themselves on read.
        migrations.RunPython(drop_stale_closes, migrations.RunPython.noop),
    ]
