# Generated by Django 6.0.2 on 2026-07-20 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_activityevent_verb'),
        ('user', '0014_businessprofile_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandTotalCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sale', 'Accumulated grand total — sales'), ('void', 'Accumulated grand total — voids'), ('return', 'Accumulated grand total — returns')], db_index=True, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('entry_count', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_total_counters', to='user.businessprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'channel'), name='uniq_grandtotal_business_channel')],
            },
        ),
        migrations.CreateModel(
            name='GrandTotalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sale', 'Accumulated grand total — sales'), ('void', 'Accumulated grand total — voids'), ('return', 'Accumulated grand total — returns')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('source_model', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('business_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_total_entries', to='user.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'channel', '-created_at'], name='activity_gr_busines_e36edc_idx'), models.Index(fields=['business', 'business_date'], name='activity_gr_busines_446280_idx')],
            },
        ),
    ]
