# Generated by Django 6.0.2 on 2026-07-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_rename_to_accumulated_grand_sales'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accumulatedgrandsalesentry',
            new_name='activity_ac_busines_dee55b_idx',
            old_name='activity_gr_busines_e36edc_idx',
        ),
        migrations.RenameIndex(
            model_name='accumulatedgrandsalesentry',
            new_name='activity_ac_busines_9b5a2f_idx',
            old_name='activity_gr_busines_446280_idx',
        ),
    ]
