# Generated by Django 6.0.2 on 2026-07-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_rename_activity_gr_busines_e36edc_idx_activity_ac_busines_dee55b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('product.created', 'Product created'), ('product.updated', 'Product updated'), ('product.archived', 'Product archived'), ('product.restored', 'Product restored'), ('product.margin_low', 'Profit margin dropped'), ('material.created', 'Material created'), ('material.updated', 'Material updated'), ('material.archived', 'Material archived'), ('material.restored', 'Material restored'), ('supplier.created', 'Supplier added'), ('supplier.updated', 'Supplier updated'), ('supplier.archived', 'Supplier archived'), ('supplier.restore', 'Supplier restored'), ('sale.completed', 'Sale completed'), ('sale.reference', 'Sale reference'), ('sale.paid', 'Sale payment recorded'), ('sale.voided', 'Sale voided'), ('purchase.recorded', 'Purchase recorded'), ('purchase.reference', 'Purchase reference'), ('purchase.paid', 'Purchase payment recorded'), ('purchase.voided', 'Purchase voided'), ('stock.adjusted', 'Stock updated'), ('stock.low', 'Low stock alert'), ('stock.critical', 'Critically low stock'), ('stock.out', 'Out of stock'), ('waste.recorded', 'Waste recorded'), ('trial.ending', 'Trial ending soon'), ('plan.expired', 'Plan expired'), ('plan.canceled', 'Subscription canceled'), ('plan.expiring', 'Subscription ending soon'), ('staff.added', 'Staff added'), ('purchase.refunded', 'Purchase refunded'), ('sale.refunded', 'Sale refunded'), ('shift.auto_closed', 'Shift auto-closed')], db_index=True, max_length=40),
        ),
    ]
