# Generated by Django 6.0.2 on 2026-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_activityevent_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclose',
            name='cash_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='dailyclose',
            name='cash_payroll',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='dailyclose',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='dailyclose',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='total_expense_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='total_material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='total_salary_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='dailyclose',
            name='total_waste_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
