# Generated by Django 6.0.2 on 2026-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_dailyclose_cash_expense_dailyclose_cash_payroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclose',
            name='completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyclose',
            name='completed_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
