# Generated by Django 6.0.2 on 2026-07-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_dailyclose_completed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclose',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='dailyclose',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyclose',
            name='purchase_count_all',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
