# Generated by Django 6.0.2 on 2026-03-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('pc', 'Piece'), ('liter', 'Liter'), ('gram', 'Gram')], default='pc', max_length=100),
        ),
    ]
