# Generated by Django 6.0.2 on 2026-03-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_alter_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='piece_per_unit',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pc', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('bottle', 'Bottle'), ('can', 'Can'), ('bag', 'Bag'), ('tray', 'Tray'), ('dozen', 'Dozen'), ('bundle', 'Bundle'), ('carton', 'Carton'), ('sachet', 'Sachet'), ('liter', 'Liter')], default='pc', max_length=100),
        ),
    ]
