# Generated by Django 6.0.2 on 2026-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pc', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('bottle', 'Bottle'), ('can', 'Can'), ('bag', 'Bag'), ('tray', 'Tray'), ('dozen', 'Dozen'), ('bundle', 'Bundle'), ('carton', 'Carton'), ('sachet', 'Sachet'), ('liter', 'Liter'), ('kg', 'Kilogram')], default='pc', max_length=100),
        ),
    ]
