# Generated by Django 6.0.2 on 2026-07-27 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_alter_material_unit'),
        ('core', '0002_initial'),
        ('user', '0016_alter_businessprofile_is_bir_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('business', 'sku'), name='unique_material_sku_per_business'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('business', 'barcode'), name='unique_material_barcode_per_business'),
        ),
    ]
