# Generated by Django 6.0.2 on 2026-03-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_material_piece_per_unit_alter_material_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='Supplier.supplier'),
        ),
    ]
