# Generated by Django 6.0.2 on 2026-07-31 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0005_backfill_material_sku'),
        ('core', '0003_category_core_catego_busines_f02c29_idx'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['business', 'unit', 'created_by'], name='Supplier_ma_busines_8684bb_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpreset',
            index=models.Index(fields=['business', 'created_by'], name='Supplier_ma_busines_794993_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'created_by'], name='Supplier_su_busines_af2672_idx'),
        ),
    ]
