# Generated by Django 6.0.2 on 2026-03-28 03:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0009_alter_supplier_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('user', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('user', 'slug')},
        ),
    ]
