# Generated by Django 6.0.2 on 2026-03-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0010_alter_material_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
