# Generated by Django 6.0.2 on 2026-04-11 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0011_alter_material_slug_alter_supplier_slug'),
        ('user', '0009_businessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='material',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='user.businessprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('user', 'slug', 'business')},
        ),
    ]
