# Generated by Django 6.0.2 on 2026-04-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0012_alter_material_unique_together_material_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='materialpreset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
