# Generated by Django 6.0.2 on 2026-04-28 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0014_supplier_business_alter_supplier_user'),
        ('user', '0003_alter_businessprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('user', 'slug', 'business')},
        ),
    ]
