# Generated by Django 6.0.2 on 2026-04-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0015_alter_supplier_unique_together'),
        ('user', '0003_alter_businessprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpreset',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='user.businessprofile'),
        ),
    ]
