# Generated by Django 6.0.2 on 2026-05-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0018_alter_materialpreset_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpresetitem',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
