# Generated by Django 6.0.2 on 2026-05-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0019_materialpresetitem_supplier_name'),
        ('user', '0005_alter_businessprofile_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialpreset',
            unique_together={('business', 'name', 'slug')},
        ),
    ]
