# Generated by Django 6.0.2 on 2026-05-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0020_alter_materialpreset_unique_together'),
        ('user', '0005_alter_businessprofile_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialpreset',
            unique_together={('business', 'name')},
        ),
    ]
