# Generated by Django 6.0.2 on 2026-05-30 20:26

import core.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0023_material_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.images.supplier_image_path),
        ),
    ]
