# Generated by Django 6.0.2 on 2026-05-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0025_material_status_supplier_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='is_active',
        ),
    ]
