# Generated by Django 6.0.2 on 2026-06-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_businessprofile_shared_cash_drawer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Share this code with staff so they can join this business.', max_length=10, null=True, unique=True),
        ),
    ]
