# Generated by Django 6.0.2 on 2026-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_businessprofile_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='accepting_staff',
            field=models.BooleanField(default=False, help_text="When on, staff can register using your invite code. Turn off when you're done hiring."),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Staff use this code to join this business.', max_length=10, null=True, unique=True),
        ),
    ]
