# Generated by Django 6.0.2 on 2026-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_businessprofile_accepting_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='receipt_width',
            field=models.CharField(choices=[('80', '80mm'), ('58', '58mm')], default='80', max_length=2),
        ),
    ]
