# Generated by Django 6.0.2 on 2026-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_businessprofile_receipt_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='enable_purchase_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='enable_sale_discount',
            field=models.BooleanField(default=False),
        ),
    ]
