# Generated by Django 6.0.2 on 2026-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_businessprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('pharmacy', 'Drugstore')], default='retail', max_length=255),
        ),
    ]
