# Generated by Django 6.0.2 on 2026-04-09 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant')], default='retail', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('business_phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number must be 11 digits.', regex='^0\\d{10}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
