# Generated by Django 6.0.2 on 2026-04-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='businessprofile',
            unique_together={('user', 'slug')},
        ),
    ]
