# Generated by Django 6.0.2 on 2026-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_sidebar_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='is_vat_registered',
            field=models.BooleanField(default=False, help_text="Turn on only if you're BIR-registered as a VAT taxpayer (usually over ₱3M yearly sales). Most small businesses are Non-VAT — leave this off."),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tin',
            field=models.CharField(blank=True, help_text='Your Tax Identification Number, shown on receipts (e.g. 123-456-789-000).', max_length=20, null=True),
        ),
    ]
