# Generated by Django 6.0.2 on 2026-04-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_businessprofile_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
