# Generated by Django 6.0.2 on 2026-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_businessprofile_is_vat_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='bir_accreditation',
            field=models.CharField(blank=True, help_text='BIR Accreditation number.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bir_min',
            field=models.CharField(blank=True, help_text='Machine Identification Number (from BIR accreditation).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bir_ptu',
            field=models.CharField(blank=True, help_text='Permit To Use (PTU) number.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_bir_active',
            field=models.BooleanField(default=False, help_text='Turn on only after BIR accredits this system to issue your official invoices. While off, the app prints a plain sales slip and you issue your own official receipt.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='is_vat_registered',
            field=models.BooleanField(default=False, help_text="Leave this off if you're a non-VAT business. Turn it on only if you're registered with BIR as VAT — receipts will then show a 12% VAT breakdown."),
        ),
    ]
