# Generated by Django 6.0.2 on 2026-07-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_businessprofile_barangay_businessprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
