# Generated by Django 6.0.2 on 2026-07-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_businessprofile_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='bir_serial_number',
            field=models.CharField(blank=True, help_text="Software licence number issued with your BIR accreditation. Printed as 'S/N' on official invoices and sales readings.", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='non_vat_type',
            field=models.CharField(choices=[('percentage', 'Percentage tax (3%)'), ('exempt', 'Exempt from VAT and percentage tax'), ('mixed', 'Percentage tax, with some exempt sales')], default='percentage', help_text="Only applies if you're NOT VAT-registered. Most small businesses pay the 3% percentage tax. Choose 'Exempt' only if you sell goods BIR exempts entirely, like rice, vegetables, fruit, livestock or poultry.", max_length=12),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registered_name',
            field=models.CharField(blank=True, help_text="The name your business is registered under with BIR, if different from the name above — e.g. your full name for a sole proprietorship. Printed on official invoices as 'Operated by'.", max_length=255, null=True),
        ),
    ]
