# Generated by Django 6.0.2 on 2026-07-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_businessprofile_bir_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='is_bir_active',
            field=models.BooleanField(default=False, help_text='Enable only when this system is BIR-ACCREDITED to issue your official invoices — it requires a POS Permit to Use (PTU) and Machine ID (MIN); being BIR-registered is not enough. Turning it on issues official invoices, starts daily Z readings, locks the ledger, and resets the invoice serial to #1. It is permanent and cannot be turned back off. While off, the app stays internal-only: it prints a non-official billing statement and you issue your own official receipt by hand.'),
        ),
    ]
