# Generated by Django 6.0.2 on 2026-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_businessprofile_is_bir_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='closing_time',
            field=models.TimeField(blank=True, help_text="Your usual closing time. Shifts a staff member forgets to clock out of are auto-closed at this time. Leave blank if you're open 24 hours — those shifts auto-close 24 hours after clock-in instead.", null=True),
        ),
    ]
