# Generated by Django 6.0.2 on 2026-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('total_salary_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_at_sale', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unsold_quantity', models.PositiveIntegerField(default=0)),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('credit', 'Store Credit')], default='cash', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('customer_changed_mind', 'Customer changed mind'), ('defective', 'Defective'), ('wrong_item', 'Wrong item'), ('expired', 'Expired'), ('amount_correction', 'Amount correction'), ('staff_error', 'Staff error'), ('other', 'Other')], default='customer_changed_mind', max_length=30)),
                ('reason_note', models.CharField(blank=True, max_length=255)),
                ('refund_total', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash refund'), ('credit', 'Store credit')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_refund', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('resellable', models.BooleanField(default=True)),
            ],
        ),
    ]
