# Generated by Django 6.0.2 on 2026-06-27 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_is_session_based_servicesession'),
        ('Sales', '0004_sale_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='Product.servicesession'),
        ),
    ]
