# Generated by Django 6.0.2 on 2026-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_sale_reference_sale_total_salary_cost_saleemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
