# Generated by Django 6.0.2 on 2026-03-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0007_purchaseitem_name'),
        ('Product', '0007_alter_product_cost_price_alter_product_selling_price'),
        ('Sales', '0005_alter_sale_total_revenue_alter_saleitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleemployee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleemployee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_employees', to='Expense.employee'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='Product.product'),
        ),
    ]
