# Generated by Django 6.0.2 on 2026-06-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_salesequence'),
        ('user', '0008_businessprofile_dashboard_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('reset_counter', models.PositiveIntegerField(default=1)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='user.businessprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
