# Generated by Django 6.0.2 on 2026-04-28 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_remove_saleitem_created_by_sale_created_by'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='user.businessprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('user', 'business')},
        ),
    ]
