# Generated by Django 6.0.2 on 2026-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_salesreturnsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='vat_class',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
