# Generated by Django 6.0.2 on 2026-04-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_sale_business_alter_sale_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='saleemployee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
