# Generated by Django 6.0.2 on 2026-04-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_alter_sale_created_at_alter_saleemployee_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together=set(),
        ),
    ]
