# Generated by Django 6.0.2 on 2026-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_sale_canceled_at_sale_canceled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='pending_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='pending_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='pending_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
