# Generated by Django 6.0.2 on 2026-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_sale_pending_amount_sale_pending_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='refund_cash',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='refund_credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'Cash refund'), ('credit', 'Deducted from balance'), ('mixed', 'Balance + cash')], default='cash', max_length=20),
        ),
    ]
