# Generated by Django 6.0.2 on 2026-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_alter_sale_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
