# Generated by Django 6.0.2 on 2026-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0012_saleitem_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
