# Generated by Django 6.0.2 on 2026-07-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_backfill_refund_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
