# Generated by Django 6.0.2 on 2026-06-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_alter_sale_date'),
        ('user', '0006_alter_businessprofile_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('credit', 'Store Credit')], default='cash', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_payments', to='user.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Sales.sale')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('customer_changed_mind', 'Customer changed mind'), ('defective', 'Defective'), ('wrong_item', 'Wrong item'), ('expired', 'Expired'), ('amount_correction', 'Amount correction'), ('void', "Void / shouldn't have happened"), ('staff_error', 'Staff error'), ('other', 'Other')], default='customer_changed_mind', max_length=30)),
                ('reason_note', models.CharField(blank=True, max_length=255)),
                ('refund_total', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash refund'), ('credit', 'Store credit')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='user.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='Sales.sale')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_refund', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('resellable', models.BooleanField(default=True)),
                ('original_sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='Sales.saleitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sales.salesreturn')),
            ],
        ),
    ]
