# Generated by Django 6.0.2 on 2026-07-20 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_alter_sale_date'),
        ('user', '0014_businessprofile_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='void_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VoidSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('reset_counter', models.PositiveIntegerField(default=1)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='user.businessprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
