# Generated by Django 6.0.2 on 2026-07-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_sale_void_reference_voidsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_id_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_tin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('', 'Regular customer'), ('sc', 'Senior Citizen'), ('pwd', 'Person with Disability'), ('naac', 'National Athlete / Coach'), ('solo_parent', 'Solo Parent')], db_index=True, default='', max_length=12),
        ),
    ]
