# Generated by Django 6.0.2 on 2026-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0016_sale_discount_id_no_sale_discount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vat_adjustment',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
