# Generated by Django 6.0.2 on 2026-07-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_sale_vat_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
