# Generated by Django 6.0.2 on 2026-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0018_salespayment_tendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='books_reset_counter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
