# Generated by Django 6.0.2 on 2026-07-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0019_sale_books_reset_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('', 'Regular customer'), ('sc', 'Senior Citizen'), ('pwd', 'PWD'), ('naac', 'National Athlete / Coach'), ('solo_parent', 'Solo Parent')], db_index=True, default='', max_length=12),
        ),
    ]
