# Generated by Django 6.0.2 on 2026-07-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0020_alter_sale_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('', 'Regular customer'), ('sc', 'SC'), ('pwd', 'PWD'), ('naac', 'NAAC'), ('solo_parent', 'SP')], db_index=True, default='', max_length=12),
        ),
    ]
