# Generated by Django 6.0.2 on 2026-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_alter_sale_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vat_adjustment',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='refund_cash',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='refund_credit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='refund_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='unit_refund',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
    ]
