# Generated by Django 6.0.2 on 2026-07-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0022_alter_sale_discount_amount_alter_sale_pending_amount_and_more'),
        ('user', '0015_businessprofile_bir_serial_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZReadingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('reset_counter', models.PositiveIntegerField(default=1)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='user.businessprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('z_counter', models.PositiveBigIntegerField()),
                ('reference', models.CharField(max_length=100)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('present_accumulated', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('previous_accumulated', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sales_for_day', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('void_count', models.PositiveIntegerField(default=0)),
                ('return_count', models.PositiveIntegerField(default=0)),
                ('is_vat_registered', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('sealed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_readings', to='user.businessprofile')),
                ('sealed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='z_readings_sealed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['business', '-date'], name='Sales_zread_busines_6d529b_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'date'), name='uniq_zreading_business_date')],
            },
        ),
    ]
