# Generated by Django 6.0.2 on 2026-07-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0025_alter_sale_is_locked_alter_sale_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
