# Generated by Django 6.0.2 on 2026-07-30 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0026_sale_total_quantity'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='Sales_sale_busines_03b31a_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='Sales_sale_busines_33a7fd_idx',
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'status', '-reference'], name='Sales_sale_busines_9ceaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'is_void', 'status', 'voided_at'], name='Sales_sale_busines_505c2a_idx'),
        ),
    ]
