# Generated by Django 6.0.2 on 2026-07-30 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0027_remove_sale_sales_sale_busines_03b31a_idx_and_more'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='outstanding',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(condition=models.Q(('outstanding__gte', 0)), fields=['business'], name='sale_receivables_idx'),
        ),
    ]
