# Generated by Django 6.0.2 on 2026-07-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0028_sale_outstanding_sale_sale_receivables_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_salary_cost',
        ),
    ]
