# Generated by Django 6.0.2 on 2026-07-30 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0029_remove_sale_total_salary_cost'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sale_receivables_idx',
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(condition=models.Q(('outstanding__gt', 0)), fields=['business'], name='sale_receivables_idx'),
        ),
    ]
