# Generated by Django 6.0.2 on 2026-07-31 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0031_backfill_outstanding'),
        ('user', '0017_businessprofile_closing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salespayment',
            index=models.Index(fields=['business', 'date', 'created_by'], name='Sales_sales_busines_9ba7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['business', 'date', 'created_by'], name='Sales_sales_busines_9b586c_idx'),
        ),
    ]
